Paginate = 5

baseURL = "https://www.nazarabrory.com"

copyright = ""

defaultContentLanguage = "en"

disqusShortname = ""

enableEmoji = true

enableRobotsTXT = true

googleAnalytics = ""

preserveTaxonomyNames = true

pygmentsCodefences = true

theme = "minimo"

title = "Nazarabrory"

[blackfriday]
hrefTargetBlank = true

[languages.en]
lang = "en"
languageName = "English"
weight = 1

[languages.id]
lang = "id"
languageName = "Indonesia"
weight = 2


[[menu.main]]
identifier = "BLog"
name = "Blogposts"
url = "/blogposts/"
weight = 2

[[menu.main]]
identifier ="About"
name = "About Me"
url = "/about/"
weight = 3

[params.assets]
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
favicon = "favicon.ico"
gopher = ""

[params.comments]
enable = false

[params.comments.isso]
dataAttrs = ""
enable = false
scriptSrc = ""

[params.comments.staticman]
apiEndpoint = "https://api.staticman.net/v2/entry"
enable = true
maxDepth = 2
repository = "minimo"
username = "MunifTanjim"

[params.comments.utterances]
enable = false
issueTerm = "pathname"
label = ""
theme = "github-light"

[params.comments.utterances.github]
repository = ""
username = ""

[params.copyright]
holder = "Nazarabrory"
prefix = ""
startYear = "2020"
suffix = ""

[params.info]
description = "Geologist, Data analyst."
title404 = "Nothing's here!"

[params.opengraph.facebook]
admins = []
appID = ""
pageID = ""

[params.opengraph.twitter]
page = ""

[params.search]
client = "fuse"

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[params.seo]
titleSeparator = "•"

[params.settings]
accentColor = "#ff7700"
archiveDateFormat = "Jan 02"
dateFormat = "2006, Jan 02"
hideEntryMeta = ["page"]
hideEntryNavigation = ["page"]
hideMainMenu = true
listDateFormat = "2006, Jan 02"
showLastmod = true
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true

[params.social]
codepen = ""
email = "nazarabrory@asia-mail.com"
facebook = ""
github = ""
gitlab = ""
google_scholar = ""
instagram = "nazarabrory"
linkedin = "nazarabrory"
telegram = "nazarabrory"
twitter = "nazarabrory"
youtube = ""

[params.widgets]
footer = ["social_menu"]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about", "sidebar_menu", "taxonomy_cloud", "search"]

[permalinks]
page = "/:slug/"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
